// <auto-generated />
using System;
using FootballManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballManager.Data.Migrations
{
    [DbContext(typeof(FootballContext))]
    [Migration("20260715125808_AddClubForm")]
    partial class AddClubForm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballManager.Data.Entities.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChampionsCups")
                        .HasColumnType("int");

                    b.Property<int>("Form")
                        .HasColumnType("int");

                    b.Property<bool>("IsBot")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFinalized")
                        .HasColumnType("bit");

                    b.Property<int>("LeagueCups")
                        .HasColumnType("int");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalCups")
                        .HasColumnType("int");

                    b.Property<int>("TrainingQuality")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Footballer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AwardQBB")
                        .HasColumnType("int");

                    b.Property<int>("AwardQBD")
                        .HasColumnType("int");

                    b.Property<int>("AwardQBV")
                        .HasColumnType("int");

                    b.Property<int?>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("ContractYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsTransferListed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Potential")
                        .HasColumnType("int");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.ToTable("Footballers");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.GameState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentPhase")
                        .HasColumnType("int");

                    b.Property<int>("CurrentSeason")
                        .HasColumnType("int");

                    b.Property<int>("CurrentWeek")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GameStates");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayClubId")
                        .HasColumnType("int");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("int");

                    b.Property<int?>("Group")
                        .HasColumnType("int");

                    b.Property<int>("HomeClubId")
                        .HasColumnType("int");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayed")
                        .HasColumnType("bit");

                    b.Property<int?>("Leg")
                        .HasColumnType("int");

                    b.Property<int?>("MVPFootballerId")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayClubId");

                    b.HasIndex("HomeClubId");

                    b.HasIndex("MVPFootballerId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("SeasonNumber", "Week");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.MatchGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("FootballerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOwnGoal")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("FootballerId");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchGoals");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.MatchLineup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("Formation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchLineups");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.MatchLineupPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FootballerId")
                        .HasColumnType("int");

                    b.Property<int>("MatchLineupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FootballerId");

                    b.HasIndex("MatchLineupId");

                    b.ToTable("MatchLineupPlayers");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.ScheduleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSeasonEnd")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTrainingBoost")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTransferOpen")
                        .HasColumnType("bit");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentType")
                        .HasColumnType("int");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Week");

                    b.ToTable("ScheduleTemplates");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.SeasonSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChampionClubId")
                        .HasColumnType("int");

                    b.Property<int?>("MVPFootballerId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TopScorerId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChampionClubId");

                    b.HasIndex("MVPFootballerId");

                    b.HasIndex("TopScorerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("SeasonSummaries");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayersPerMatch")
                        .HasColumnType("int");

                    b.Property<string>("RewardByRank")
                        .HasColumnType("text");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("int");

                    b.Property<int>("TeamsCount")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.TournamentClub", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<int>("Drawn")
                        .HasColumnType("int");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("int");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("int");

                    b.Property<int?>("Group")
                        .HasColumnType("int");

                    b.Property<int>("Lost")
                        .HasColumnType("int");

                    b.Property<int>("Played")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("Won")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentClubs");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ContractYears")
                        .HasColumnType("int");

                    b.Property<int>("FootballerId")
                        .HasColumnType("int");

                    b.Property<int?>("FromClubId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("ToClubId")
                        .HasColumnType("int");

                    b.Property<decimal>("TransferFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FootballerId");

                    b.HasIndex("FromClubId");

                    b.HasIndex("ToClubId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Footballer", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Club", "Club")
                        .WithMany("Footballers")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Club");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Match", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Club", "AwayClub")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayClubId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballManager.Data.Entities.Club", "HomeClub")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Data.Entities.Footballer", "MVPFootballer")
                        .WithMany()
                        .HasForeignKey("MVPFootballerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballManager.Data.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayClub");

                    b.Navigation("HomeClub");

                    b.Navigation("MVPFootballer");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.MatchGoal", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Data.Entities.Footballer", "Footballer")
                        .WithMany()
                        .HasForeignKey("FootballerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Data.Entities.Match", "Match")
                        .WithMany("Goals")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Footballer");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.MatchLineup", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Club", "Club")
                        .WithMany("MatchLineups")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballManager.Data.Entities.Match", "Match")
                        .WithMany("MatchLineups")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Match");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.MatchLineupPlayer", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Footballer", "Footballer")
                        .WithMany()
                        .HasForeignKey("FootballerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FootballManager.Data.Entities.MatchLineup", "MatchLineup")
                        .WithMany("Players")
                        .HasForeignKey("MatchLineupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Footballer");

                    b.Navigation("MatchLineup");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.SeasonSummary", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Club", "ChampionClub")
                        .WithMany()
                        .HasForeignKey("ChampionClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballManager.Data.Entities.Footballer", "MVPFootballer")
                        .WithMany()
                        .HasForeignKey("MVPFootballerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballManager.Data.Entities.Footballer", "TopScorer")
                        .WithMany()
                        .HasForeignKey("TopScorerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FootballManager.Data.Entities.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChampionClub");

                    b.Navigation("MVPFootballer");

                    b.Navigation("TopScorer");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.TournamentClub", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Club", "Club")
                        .WithMany("TournamentClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballManager.Data.Entities.Tournament", "Tournament")
                        .WithMany("TournamentClubs")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Transfer", b =>
                {
                    b.HasOne("FootballManager.Data.Entities.Footballer", "Footballer")
                        .WithMany("Transfers")
                        .HasForeignKey("FootballerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FootballManager.Data.Entities.Club", "FromClub")
                        .WithMany()
                        .HasForeignKey("FromClubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FootballManager.Data.Entities.Club", "ToClub")
                        .WithMany()
                        .HasForeignKey("ToClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Footballer");

                    b.Navigation("FromClub");

                    b.Navigation("ToClub");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Club", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("Footballers");

                    b.Navigation("HomeMatches");

                    b.Navigation("MatchLineups");

                    b.Navigation("TournamentClubs");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Footballer", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Match", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("MatchLineups");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.MatchLineup", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("FootballManager.Data.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TournamentClubs");
                });
#pragma warning restore 612, 618
        }
    }
}
